### ISSUE TITLE
Allow dedicated server usage?

### ISSUE THREAD

**Issue by l8nite** [thejhoffman/FuelEternal#1]
Will this work if installed on a dedicated server instead? Currently it is not able to load due to this attribute on the class:
```
	[BepInProcess("valheim.exe")]
```

**Comment by FAiLSEED** [comment]
I'm running a dedicated server and would adore having this!  I've tried torcheseternal which boots up ok in bepinex, but doesn't seem to effect the actual fuel in torches etc.  If there is anyway this could be adjusted to work server-side only would be absolutely amazing!  Thanks from my xbox friends and I =)

**Comment by l8nite** [comment]
> I'm running a dedicated server and would adore having this! I've tried torcheseternal which boots up ok in bepinex, but doesn't seem to effect the actual fuel in torches etc. If there is anyway this could be adjusted to work server-side only would be absolutely amazing! Thanks from my xbox friends and I =)

For what it's worth, I started using this mod client-side which has been working well: https://valheim.thunderstore.io/package/TastyChickenLegs/NoSmokeStayLit/

**Comment by thejhoffman** [comment]
I updated the mod to remove the `[BepInProcess("valheim.exe")]` line which should enable it to work in a server environment now. v1.2.1 is live on both Nexus and Thunderstore.

I know that you have switched to using another mod, which is fine. However, if you could test it out and let me know if it works or not. I can look into updating it if changes might be needed.

Otherwise, I will close this issue for now and will reopen if it needs further attention.

**Comment by bblough** [comment]
Hi.  Thanks for this mod - it has worked great for me client-side in single player. 

I've recently started a new playthrough on a dedicated server with family/friends and was hoping to run this server-side.  

The module is getting loaded:

```[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Info   :   BepInEx] Detected Unity version: v6000.0.58f2
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [AzuExtendedPlayerInventory 1.4.12]
[Info   :   BepInEx] Loading [FuelEternal 1.2.1]
[Message:   BepInEx] Chainloader startup complete
```

and I'm using the default config (torches, campfires, etc. are refueled, but no smelters, eitr, etc).

None of the torches or campfires are getting topped up unless I also load the mod client side.  I was hoping that I could run this on the server and not need to load it on the individual clients.

Is this intended to be possible?  If so, is there anything I can do to help troubleshoot the issue?
